language: c
compiler: gcc
install: true
#sudo: required
os: linux

jobs:
  include:
   - name: "AMD64 trusty accessdaemon gcc7"
     env: BUILD_ACCESSMODE=accessdaemon LIKWID_COMPILER=GCC COMPILER_BINARY=gcc-7 LIKWID_BENCHMARK=copy
     arch: amd64
     dist: trusty
     addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
   - name: "AMD64 trusty direct gcc7"
     env: BUILD_ACCESSMODE=direct LIKWID_COMPILER=GCC COMPILER_BINARY=gcc-7 LIKWID_BENCHMARK=copy
     arch: amd64
     dist: trusty
     addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
   - name: "AMD64 trusty perf_event gcc7"
     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCC COMPILER_BINARY=gcc-7 LIKWID_BENCHMARK=copy
     arch: amd64
     dist: trusty
     addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
   - name: "AMD64 trusty accessdaemon"
     env: BUILD_ACCESSMODE=accessdaemon LIKWID_COMPILER=GCC LIKWID_BENCHMARK=copy
     arch: amd64
     dist: trusty
   - name: "AMD64 trusty direct"
     env: BUILD_ACCESSMODE=direct LIKWID_COMPILER=GCC LIKWID_BENCHMARK=copy
     arch: amd64
     dist: trusty
   - name: "AMD64 trusty perf_event"
     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCC LIKWID_BENCHMARK=copy
     arch: amd64
     dist: trusty
   - name: "AMD64 xenial accessdaemon"
     env: BUILD_ACCESSMODE=accessdaemon LIKWID_COMPILER=GCC LIKWID_BENCHMARK=copy
     arch: amd64
     dist: xenial
   - name: "AMD64 xenial direct"
     env: BUILD_ACCESSMODE=direct LIKWID_COMPILER=GCC LIKWID_BENCHMARK=copy
     arch: amd64
     dist: xenial
   - name: "AMD64 xenial perf_event"
     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCC LIKWID_BENCHMARK=copy
     arch: amd64
     dist: xenial
   - name: "AMD64 xenial accessdaemon"
     env: BUILD_ACCESSMODE=accessdaemon LIKWID_COMPILER=GCC LIKWID_BENCHMARK=copy
     arch: amd64
     dist: bionic
   - name: "AMD64 bionic direct"
     env: BUILD_ACCESSMODE=direct LIKWID_COMPILER=GCC LIKWID_BENCHMARK=copy
     arch: amd64
     dist: bionic
   - name: "AMD64 bionic perf_event"
     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCC LIKWID_BENCHMARK=copy
     arch: amd64
     dist: bionic
   - name: "PPC xenial"
     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCCPOWER LIKWID_BENCHMARK=copy_vsx4
     arch: ppc64le
     dist: xenial
   - name: "ARMv8 trusty"
     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCCARMv8 LIKWID_BENCHMARK=copy
     arch: arm64
     dist: trusty
   - name: "ARMv8 xenial"
     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCCARMv8 LIKWID_BENCHMARK=copy
     arch: arm64
     dist: xenial
   - name: "ARMv8 bionic"
     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCCARMv8 LIKWID_BENCHMARK=copy
     arch: arm64
     dist: bionic
before_install:
  - sudo apt-get -y install openmpi
script:
#  - sed -i -e s+'CC  = gcc.*'+'CC  = gcc-7'+g make/include_GCC.mk
  - echo "ACCESSMODE=${BUILD_ACCESSMODE}"
  - echo "COMPILER=${LIKWID_COMPILER}"
  - echo "COMPILER_BINARY=${COMPILER_BINARY}"
  - echo "LIKWID_BENCHMARK=${LIKWID_BENCHMARK}"
  - if [ ! -z "$COMPILER_BINARY" ]; then sed -i -e s+'CC  = gcc.*'+"CC  = $COMPILER_BINARY"+g make/include_${LIKWID_COMPILER}.mk; fi
  - make ACCESSMODE="${BUILD_ACCESSMODE}" COMPILER="${LIKWID_COMPILER}"
  - sudo make ACCESSMODE="${BUILD_ACCESSMODE}" COMPILER="${LIKWID_COMPILER}" install
  - /usr/local/bin/likwid-topology -c -C -g
  - /usr/local/bin/likwid-pin -p
  - /usr/local/bin/likwid-mpirun -np 2 -d hostname
  - if [ "${TRAVIS_CPU_ARCH}" == "amd64" ]; then sudo modprobe msr; ls -la /dev/cpu/*; ls -la /usr/local/sbin/*; fi
  - make -C test streamGCC
  - /usr/local/bin/likwid-perfctr -i
#  - echo "LIKWID_BENCHMARK=${LIKWID_BENCHMARK}"
  - if [ "${TRAVIS_CPU_ARCH}" != "ppc64le" ]; then /usr/local/bin/likwid-bench -t "${LIKWID_BENCHMARK}" -w N:100MB:2; fi
