language: c
compiler: gcc
install: true
dist:
  - trusty
  - xenial
  - bionic
os: linux
arch:
  - amd64
  - ppc64le
  - arm64
sudo: required
addons: {
    apt: {
        sources: [
            ubuntu-toolchain-r-test
        ],
    packages: [
        "gcc-7"
    ]
    }
}
env:
  - BUILD_ACCESSMODE=accessdaemon
  - BUILD_ACCESSMODE=direct
  - BUILD_ACCESSMODE=perf_event
script:
#  - sed -i -e s+'CC  = gcc.*'+'CC  = gcc-7'+g make/include_GCC.mk
  - if [ "${TRAVIS_CPU_ARCH}" == "amd64" ]; then export LIKWID_COMPILER=GCC; sed -i -e s+'CC  = gcc.*'+'CC  = gcc-7'+g make/include_GCC.mk; fi
  - if [ "${TRAVIS_CPU_ARCH}" == "ppc64le" ]; then export LIKWID_COMPILER=GCCPOWER; sed -i -e s+'CC  = gcc.*'+'CC  = gcc-7'+g make/include_GCCPOWER.mk; fi
  - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then export LIKWID_COMPILER=GCCARMv8; sed -i -e s+'CC  = gcc.*'+'CC  = gcc-7'+g make/include_GCCARMv8.mk; fi
  - make ACCESSMODE=${BUILD_ACCESSMODE} COMPILER=${LIKWID_COMPILER}
  - sudo make ACCESSMODE=${BUILD_ACCESSMODE} COMPILER=${LIKWID_COMPILER} install
  - /usr/local/bin/likwid-topology -c -C -g
  - /usr/local/bin/likwid-pin -p
  - sudo modprobe msr
  - ls -la /dev/cpu/*
  - ls -la /usr/local/sbin/*
  - make -C test streamGCC
  - /usr/local/bin/likwid-perfctr -i
  - /usr/local/bin/likwid-bench -t copy -w N:100MB:2
