language: c
compiler: gcc
install: true
#sudo: required
os: linux

jobs:
  include:
#   - os: linux
#     env: BUILD_ACCESSMODE=accessdaemon LIKWID_COMPILER=GCC COMPILER_BINARY=gcc-7
#     arch: amd64
#     dist: trusty
#     addons: {
#        apt: {
#            sources: [
#                ubuntu-toolchain-r-test
#            ],
#        packages: [
#            "gcc-7"
#        ]
#        }
#    }
#   - os: linux
#     env: BUILD_ACCESSMODE=direct LIKWID_COMPILER=GCC COMPILER_BINARY=gcc-7
#     arch: amd64
#     dist: trusty
#     addons: {
#        apt: {
#            sources: [
#                ubuntu-toolchain-r-test
#            ],
#        packages: [
#            "gcc-7"
#        ]
#        }
#    }
#   - os: linux
#     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCC COMPILER_BINARY=gcc-7
#     arch: amd64
#     dist: trusty
#     addons: {
#        apt: {
#            sources: [
#                ubuntu-toolchain-r-test
#            ],
#        packages: [
#            "gcc-7"
#        ]
#        }
#    }
#   - os: linux
#     env: BUILD_ACCESSMODE=accessdaemon LIKWID_COMPILER=GCC
#     arch: amd64
#     dist: xenial
#   - os: linux
#     env: BUILD_ACCESSMODE=direct LIKWID_COMPILER=GCC
#     arch: amd64
#     dist: xenial
#   - os: linux
#     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCC
#     arch: amd64
#     dist: xenial
#   - os: linux
#     env: BUILD_ACCESSMODE=accessdaemon LIKWID_COMPILER=GCC
#     arch: amd64
#     dist: bionic
#   - os: linux
#     env: BUILD_ACCESSMODE=direct LIKWID_COMPILER=GCC
#     arch: amd64
#     dist: bionic
#   - os: linux
#     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCC
#     arch: amd64
#     dist: bionic
#   - name: "PPC trusty"
#     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCCPOWER COMPILER_BINARY=gcc-7
#     arch: ppc64le
#     dist: trusty
#     addons: {
#        apt: {
#            sources: [
#                ubuntu-toolchain-r-test
#            ],
#        packages: [
#            "gcc-7"
#        ]
#        }
#    }
#   - name: "PPC xenial"
#     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCCPOWER
#     arch: ppc64le
#     dist: xenial
#   - name: "PPC bionic"
#     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCCPOWER
#     arch: ppc64le
#     dist: bionic
   - name: "PPC"
     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCCPOWER
     arch: ppc64le
   - name: "ARMv8 trusty"
     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCCARMv8
     arch: arm64
     dist: trusty
#   - os: linux
#     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCCARMv8
#     arch: arm64
#     dist: xenial
#   - os: linux
#     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCCARMv8
#     arch: arm64
#     dist: bionic
script:
#  - sed -i -e s+'CC  = gcc.*'+'CC  = gcc-7'+g make/include_GCC.mk
  - echo "ACCESSMODE=${BUILD_ACCESSMODE} COMPILER=${LIKWID_COMPILER} COMPILER_BINARY=${COMPILER_BINARY}"
  - if [ ! -z "$COMPILER_BINARY" ]; then sed -i -e s+'CC  = gcc.*'+"CC  = $COMPILER_BINARY"+g make/include_${LIKWID_COMPILER}.mk; grep "CC" make/include_${LIKWID_COMPILER}.mk; fi
  - make ACCESSMODE=${BUILD_ACCESSMODE} COMPILER=${LIKWID_COMPILER}
  - sudo make ACCESSMODE=${BUILD_ACCESSMODE} COMPILER=${LIKWID_COMPILER} install
  - /usr/local/bin/likwid-topology -c -C -g
  - /usr/local/bin/likwid-pin -p
  - if [ "${TRAVIS_CPU_ARCH}" == "amd64" ]; then sudo modprobe msr; ls -la /dev/cpu/*; ls -la /usr/local/sbin/*; fi
  - make -C test streamGCC
  - /usr/local/bin/likwid-perfctr -i
  - /usr/local/bin/likwid-bench -t copy -w N:100MB:2
