language: c
compiler: gcc
install: true
sudo: required
addons: {
    apt: {
        sources: [
            ubuntu-toolchain-r-test
        ],
    packages: [
        "gcc-7"
    ]
    }
}
matrix:
  include:
   - os: linux
     env: BUILD_ACCESSMODE=accessdaemon LIKWID_COMPILER=GCC
     arch: amd64
     dist: trusty
   - os: linux
     env: BUILD_ACCESSMODE=direct LIKWID_COMPILER=GCC
     arch: amd64
     dist: trusty
   - os: linux
     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCC
     arch: amd64
     dist: trusty
   - os: linux
     env: BUILD_ACCESSMODE=accessdaemon LIKWID_COMPILER=GCC
     arch: amd64
     dist: xenial
   - os: linux
     env: BUILD_ACCESSMODE=direct LIKWID_COMPILER=GCC
     arch: amd64
     dist: xenial
   - os: linux
     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCC
     arch: amd64
     dist: xenial
   - os: linux
     env: BUILD_ACCESSMODE=accessdaemon LIKWID_COMPILER=GCC
     arch: amd64
     dist: bionic
   - os: linux
     env: BUILD_ACCESSMODE=direct LIKWID_COMPILER=GCC
     arch: amd64
     dist: bionic
   - os: linux
     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCC
     arch: amd64
     dist: bionic
   - os: linux
     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCCPOWER
     arch: ppc64le
     dist: trusty
   - os: linux
     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCCPOWER
     arch: ppc64le
     dist: xenial
   - os: linux
     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCCPOWER
     arch: ppc64le
     dist: bionic
   - os: linux
     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCCARMv8
     arch: arm64
     dist: trusty
   - os: linux
     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCCARMv8
     arch: arm64
     dist: xenial
   - os: linux
     env: BUILD_ACCESSMODE=perf_event LIKWID_COMPILER=GCCARMv8
     arch: arm64
     dist: bionic
script:
#  - sed -i -e s+'CC  = gcc.*'+'CC  = gcc-7'+g make/include_GCC.mk
  - echo "ACCESSMODE=${BUILD_ACCESSMODE} COMPILER=${LIKWID_COMPILER}"
  - make ACCESSMODE=${BUILD_ACCESSMODE} COMPILER=${LIKWID_COMPILER}
  - sudo make ACCESSMODE=${BUILD_ACCESSMODE} COMPILER=${LIKWID_COMPILER} install
  - /usr/local/bin/likwid-topology -c -C -g
  - /usr/local/bin/likwid-pin -p
  - sudo modprobe msr
  - ls -la /dev/cpu/*
  - ls -la /usr/local/sbin/*
  - make -C test streamGCC
  - /usr/local/bin/likwid-perfctr -i
  - /usr/local/bin/likwid-bench -t copy -w N:100MB:2
